### ISSUE TITLE
Completions break when user input is longer than a chosen suggestion

### ISSUE THREAD

**Issue by amjith** [jonathanslenders/python-prompt-toolkit#116]
I'm trying a new fuzzy completer for prompt_toolkit and during an experiment I uncovered the following bug.

Try the following example script: 

```
#!/usr/bin/env python
from __future__ import unicode_literals

from prompt_toolkit.completion import Completer, Completion
from prompt_toolkit.shortcuts import get_input


animals = [
    'alligator',
    'fish',
    'turtle',
    ]

class FuzzyCompleter(Completer):
    def get_completions(self, document, complete_event):
        word_before_cursor = document.get_word_before_cursor(WORD=True)
        yield Completion(animals[0], -len(word_before_cursor))

def main():
    text = get_input('Give some animals: ', completer=FuzzyCompleter())
    print('You said: %s' % text)

if __name__ == '__main__':
    main()

```

Save it as auto_fuzzy.py and run it. `python auto_fuzzy.py`. 

In the user input type `abcdefaalkjafoij` (or something quite long) and then press `<tab>`. It will crash with the following error message: 

```
Give some animals: ads;kljaoijasdlkjf;alkjTraceback (most recent call last):
  File "auto_fuzzy.py", line 24, in <module>
    main()
  File "auto_fuzzy.py", line 20, in main
    text = get_input('Give some animals: ', completer=FuzzyCompleter())
  File "/Users/amjith/Dropbox/code/python/python-prompt-toolkit/prompt_toolkit/shortcuts.py", line 286, in get_input
    document = cli.read_input()
  File "/Users/amjith/Dropbox/code/python/python-prompt-toolkit/prompt_toolkit/interface.py", line 321, in read_input
    self.eventloop.run(self.stdin, self.create_eventloop_callbacks())
  File "/Users/amjith/Dropbox/code/python/python-prompt-toolkit/prompt_toolkit/eventloop/posix.py", line 81, in run
    c()
  File "/Users/amjith/Dropbox/code/python/python-prompt-toolkit/prompt_toolkit/interface.py", line 570, in callback
    self._redraw()
  File "/Users/amjith/Dropbox/code/python/python-prompt-toolkit/prompt_toolkit/interface.py", line 293, in _redraw
    self.renderer.render(self, self.layout, self.style)
  File "/Users/amjith/Dropbox/code/python/python-prompt-toolkit/prompt_toolkit/renderer.py", line 307, in render
    extended_height=size.rows,
  File "/Users/amjith/Dropbox/code/python/python-prompt-toolkit/prompt_toolkit/layout/containers.py", line 81, in write_to_screen
    dimensions = [c.height(cli, write_position.width) for c in self.children]
  File "/Users/amjith/Dropbox/code/python/python-prompt-toolkit/prompt_toolkit/layout/containers.py", line 239, in height
    return self.content.height(cli, width)
  File "/Users/amjith/Dropbox/code/python/python-prompt-toolkit/prompt_toolkit/layout/containers.py", line 594, in height
    preferred_height = self.content.preferred_height(cli, width)
  File "/Users/amjith/Dropbox/code/python/python-prompt-toolkit/prompt_toolkit/layout/controls.py", line 237, in preferred_height
    screen = self.create_screen(cli, width, None)
  File "/Users/amjith/Dropbox/code/python/python-prompt-toolkit/prompt_toolkit/layout/controls.py", line 378, in create_screen
    x, y = cursor_position_to_xy(buffer.complete_state.original_document.cursor_position)
  File "/Users/amjith/Dropbox/code/python/python-prompt-toolkit/prompt_toolkit/layout/controls.py", line 336, in cursor_position_to_xy
    return indexes_to_pos[cursor_position]
KeyError: 42
```

The cause is the user input is longer than the completion that was recommended when the <tab> key is pressed. This exception doesn't happen if the user input is shorter than the suggestion. 

edit: Escape `<tab>` so github doesn't think it's a html tag.

**Comment by jonathanslenders** [comment]
That's a serious bug. Thanks for reporting, @amjith. I'll fix it asap.

**Comment by jonathanslenders** [comment]
Fixed in: https://github.com/jonathanslenders/python-prompt-toolkit/commit/0b4a2424b1ed3cf4c4975492f34f37d53080ba0d
