### ISSUE TITLE
python-prompt-toolkit git version installation fails

### ISSUE THREAD

**Issue by Vvpzz** [jonathanslenders/python-prompt-toolkit#177]
Hello,

trying to install the git version fails with the following input :
bla@cpu:~$ pip3 install git+https://github.com/jonathanslenders/python-prompt-toolkit.git
Downloading/unpacking git+https://github.com/jonathanslenders/python-prompt-toolkit.git
  Cloning https://github.com/jonathanslenders/python-prompt-toolkit.git to /tmp/pip-cg2o9ss0-build
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 304, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python3/dist-packages/pip/req.py", line 1230, in prepare_files
    req_to_install.run_egg_info()
  File "/usr/lib/python3/dist-packages/pip/req.py", line 295, in run_egg_info
    logger.notify('Running setup.py (path:%s) egg_info for package from %s' % (self.setup_py, self.url))
  File "/usr/lib/python3/dist-packages/pip/req.py", line 266, in setup_py
    import setuptools
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/usr/share/python-wheels/setuptools-12.2-py2.py3-none-any.whl/setuptools/__init__.py", line 11, in <module>
    from setuptools.extension import Extension
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/usr/share/python-wheels/setuptools-12.2-py2.py3-none-any.whl/setuptools/extension.py", line 8, in <module>
    from .dist import _get_unpatched
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/usr/share/python-wheels/setuptools-12.2-py2.py3-none-any.whl/setuptools/dist.py", line 21, in <module>
    packaging = pkg_resources.packaging
AttributeError: 'module' object has no attribute 'packaging'

Storing debug log for failure in /home/bla/.pip/pip.log

Any idea of the problem root cause? I use python 3.4.3. 

The regular `pip3 install prompt-toolkit` works fine, but I need the last version, because of [this bug](https://github.com/click-contrib/click-repl/issues/2) linked to [this one (fixed)] (https://github.com/jonathanslenders/python-prompt-toolkit/issues/150).

Thx

**Comment by untitaker** [comment]
Nvm, sorry, it was an issue on my side.

**Comment by jonathanslenders** [comment]
I'm closing this, because we have done a new release to Pypi in the meantime. Feel free to reopen if this is still an issue.
