### ISSUE TITLE
Problem with functions I create

### ISSUE THREAD

**Issue by adamtwiss** [jonathanslenders/python-prompt-toolkit#19]
To recreate - define a simple function, and try and call it.

```
Adams-MacBook-Pro:tmp adam$ ptpython 
In [1]: def square(x):
     2.     return x*x                            
     3.                        

In [2]: square(Exception in thread Thread-36:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 808, in __bootstrap_inner
    self.run()
  File "/Library/Python/2.7/site-packages/prompt_toolkit/__init__.py", line 200, in run
    callback()
  File "/Library/Python/2.7/site-packages/prompt_toolkit/__init__.py", line 440, in run 2.7.5                                                         
    completions = list(line.completer.get_completions(document))
  File "/Library/Python/2.7/site-packages/prompt_toolkit/contrib/python_input.py", line 449, in get_completions
    for c in script.completions():
  File "/Library/Python/2.7/site-packages/jedi/api/__init__.py", line 161, in completions
    for call_sig in self.call_signatures():
  File "/Library/Python/2.7/site-packages/jedi/api/__init__.py", line 574, in call_signatures
    self._pos, user_stmt)
  File "/Library/Python/2.7/site-packages/jedi/cache.py", line 90, in wrapper
    value = optional_callable()
  File "/Library/Python/2.7/site-packages/jedi/api/__init__.py", line 572, in <lambda>
    _callable = lambda: self._evaluator.eval_call(stmt_el)
  File "/Library/Python/2.7/site-packages/jedi/evaluate/__init__.py", line 226, in eval_call
    return self.eval_call_path(path, par, s.start_pos)
  File "/Library/Python/2.7/site-packages/jedi/evaluate/__init__.py", line 240, in eval_call_path
    search_global=True)
  File "/Library/Python/2.7/site-packages/jedi/evaluate/__init__.py", line 113, in find_types
    return f.find(scopes, resolve_decorator, search_global)
  File "/Library/Python/2.7/site-packages/jedi/debug.py", line 51, in wrapper
    result = func(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/jedi/evaluate/finder.py", line 46, in find
    names = self.filter_name(scopes)
  File "/Library/Python/2.7/site-packages/jedi/evaluate/finder.py", line 89, in filter_name
    scope = name.parent.parent
  File "/Library/Python/2.7/site-packages/jedi/cache.py", line 139, in wrapper
    result = func(self)
  File "/Library/Python/2.7/site-packages/jedi/api/interpreter.py", line 69, in parent
    module = __import__(module_name)
TypeError: __import__() argument 1 must be string, not None
```
Note the exception occurs after hitting the bracket in "square(" after calling the first time

This is OS X Mavericks with latest standard OS python (e.g. standard/latest Mac)

```
Adams-MacBook-Pro:tmp adam$ uname -a     
Darwin Adams-MacBook-Pro.local 13.4.0 Darwin Kernel Version 13.4.0: Sun Aug 17 19:50:11 PDT 2014; root:xnu-2422.115.4~1/RELEASE_X86_64 x86_64
Adams-MacBook-Pro:tmp adam$ python -V
Python 2.7.5
Adams-MacBook-Pro:tmp adam$ pip freeze | grep prompt
prompt-toolkit==0.18
```

**Comment by jonathanslenders** [comment]
Hi all, closing this ticket because ``ptpython`` was removed from ``prompt-toolkit`` and got its own repository: https://github.com/jonathanslenders/ptpython/ . Further, the ``Jedi`` library for ``ptpython`` has been upgraded and we handle all known exceptions already. Let's create a new ticket if it happens again.
