### ISSUE TITLE
Error on startup in git bash on Windows

### ISSUE THREAD

**Issue by takluyver** [jonathanslenders/python-prompt-toolkit#220]
I see this error setting up prompt_toolkit inside git-bash on Windows. It appears that git-bash can handle at least some ansi escape sequences (I just tried changing colour manually), so maybe if we detect this, we can try treating it like a Unix terminal. It may not handle enough of the escapes, though.

I'm happy enough saying we don't support git-bash - the current version of IPython doesn't really work in it either - but I'm sure this will come up, and if it's easily solved, so much the better. I'm happy to test on Windows if that's difficult for you.

```
Traceback (most recent call last):
  File "C:\Users\Thomas\Miniconda3\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Thomas\Miniconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Thomas\Code\ipython\IPython\terminal\ptshell.py", line 204, in <module>
    PTInteractiveShell.instance().interact()
  File "C:\Users\Thomas\Miniconda3\lib\site-packages\traitlets\config\configurable.py", line 380, in instance
    inst = cls(*args, **kwargs)
  File "C:\Users\Thomas\Code\ipython\IPython\terminal\ptshell.py", line 165, in __init__
    self.init_prompt_toolkit_cli()
  File "C:\Users\Thomas\Code\ipython\IPython\terminal\ptshell.py", line 147, in init_prompt_toolkit_cli
    eventloop=create_eventloop(self.inputhook))
  File "C:\Users\Thomas\Miniconda3\lib\site-packages\prompt_toolkit\interface.py", line 85, in __init__
    mouse_support=application.mouse_support)
  File "C:\Users\Thomas\Miniconda3\lib\site-packages\prompt_toolkit\renderer.py", line 248, in __init__
    self.reset(_scroll=True)
  File "C:\Users\Thomas\Miniconda3\lib\site-packages\prompt_toolkit\renderer.py", line 280, in reset
    self.output.scroll_buffer_to_prompt()
  File "C:\Users\Thomas\Miniconda3\lib\site-packages\prompt_toolkit\terminal\win32_output.py", line 247, in scroll_buffer_to_prompt
    sr = info.srWindow
AttributeError: 'NoneType' object has no attribute 'srWindow'
```

**Comment by jonathanslenders** [comment]
Hi Thomas,

Git-windows is a special environment, because it usen Mingw/Cygwin to emulate the Posix API. That means that it's not a real Windows console. The application itself emulates a vt100 terminal.

It is possible to run native Windows applications in it, but they won't see a real console. python.exe for instance also blocks on start-up. Running the Windows build of Python in here means that some libraries are not available (termios, tty, fcntl, ...). However, they are required to run in a posix environment. Without these, we cannot for instance determine the terminal size.

What we would need is a Python build for this environment. I think the Python build for Cygwin should work fine.

There is a workaround however. Winpty [0] allows software that expects a Windows console to run in this kind of terminal. The following for instance works fine: ``winpty python -m ptpython``

So far my understanding of how git-bash works.
Hope that helps.
Jonathan

[0] https://github.com/rprichard/winpty

**Comment by takluyver** [comment]
Thanks! I've come across winpty before from the other side - we have a JS terminal emulator in the notebook web interface, and people wanted it to work on Windows - but paled at the installation instructions.

So I think we'll say git bash is unsupported, and let the braver souls experiment with cygwin if they choose to.
