### ISSUE TITLE
master breaks up/down arrows on Windows

### ISSUE THREAD

**Issue by jorisvandenbossche** [jonathanslenders/python-prompt-toolkit#316]
I was testing master for https://github.com/ipython/ipython/issues/9600, and I notice that with one of the latest commits, the up/down arrows don't work anymore (couple of hours ago this was not yet the case).

Traceback of pressing up arrow (and it exits afterwards):

```
In [4]:
Traceback (most recent call last):
  File "c:\anaconda\envs\devel\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\anaconda\envs\devel\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Anaconda\envs\devel\Scripts\ipython.exe\__main__.py", line 9, in <mod
ule>
    sys.exit(start_ipython())
  File "c:\anaconda\envs\devel\lib\site-packages\IPython\__init__.py", line 119,
 in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "c:\anaconda\envs\devel\lib\site-packages\traitlets\config\application.py
", line 596, in launch_instance
    app.start()
  File "c:\anaconda\envs\devel\lib\site-packages\IPython\terminal\ipapp.py", lin
e 348, in start
    self.shell.mainloop()
  File "c:\anaconda\envs\devel\lib\site-packages\IPython\terminal\ptshell.py", l
ine 431, in mainloop
    self.interact()
  File "c:\anaconda\envs\devel\lib\site-packages\IPython\terminal\ptshell.py", l
ine 414, in interact
    code = self.prompt_for_code()
  File "c:\anaconda\envs\devel\lib\site-packages\IPython\terminal\ptshell.py", l
ine 357, in prompt_for_code
    pre_run=self.pre_prompt, reset_current_buffer=True)
  File "c:\anaconda\envs\devel\lib\site-packages\prompt_toolkit\interface.py", l
ine 388, in run
    self.eventloop.run(self.input, self.create_eventloop_callbacks())
  File "c:\anaconda\envs\devel\lib\site-packages\prompt_toolkit\eventloop\win32.
py", line 76, in run
    keys = self._console_input_reader.read()
  File "c:\anaconda\envs\devel\lib\site-packages\prompt_toolkit\terminal\win32_i
nput.py", line 149, in read
    key_presses = self._event_to_key_presses(ev)
  File "c:\anaconda\envs\devel\lib\site-packages\prompt_toolkit\terminal\win32_i
nput.py", line 171, in _event_to_key_presses
    result = KeyPress(self.keycodes[ev.VirtualKeyCode], '')
  File "c:\anaconda\envs\devel\lib\site-packages\prompt_toolkit\key_binding\inpu
t_processor.py", line 35, in __init__
    assert data is None or isinstance(data, six.text_type)
AssertionError

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True
```

**Comment by jonathanslenders** [comment]
Thanks for reporting this! I think I need to add ``from __future__ import unicode_literals`` at the top of ``prompt_toolkit.terminal.win32_input.py``.

**Comment by Carreau** [comment]
> Thanks for reporting this! I think I need to add from __future__ import unicode_literals at the top of prompt_toolkit.terminal.win32_input.py

Well, you can also remove support for Python 2 :-D

**Comment by jonathanslenders** [comment]
It's easy enough to fix :)  https://github.com/jonathanslenders/python-prompt-toolkit/commit/1f344012a4629a7ef54ddbf885bd36b68bec248c

I reproduced the issue on Windows 7, Python 2.7, and now it works. I close this issue. Feel free to reopen if this doesn't fix it.

**Comment by jorisvandenbossche** [comment]
I can confirm it is fixed!
