### ISSUE TITLE
Esc+- followed by backspace generates AssertionError

### ISSUE THREAD

**Issue by haridsv** [jonathanslenders/python-prompt-toolkit#345]
While using iPython 5, I got the below exception when I pressed Esc+- (which showed "Repeat: -1") and then pressed backspace:

```
Traceback (most recent call last):
  File "/Users/hdara/bin/python/bin/ipython", line 11, in <module>
    sys.exit(start_ipython())
  File "/Users/hdara/bin/python/lib/python2.7/site-packages/IPython/__init__.py", line 119, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/Users/hdara/bin/python/lib/python2.7/site-packages/traitlets/config/application.py", line 596, in launch_instance
    app.start()
  File "/Users/hdara/bin/python/lib/python2.7/site-packages/IPython/terminal/ipapp.py", line 348, in start
    self.shell.mainloop()
  File "/Users/hdara/bin/python/lib/python2.7/site-packages/IPython/terminal/interactiveshell.py", line 402, in mainloop
    self.interact()
  File "/Users/hdara/bin/python/lib/python2.7/site-packages/IPython/terminal/interactiveshell.py", line 385, in interact
    code = self.prompt_for_code()
  File "/Users/hdara/bin/python/lib/python2.7/site-packages/IPython/terminal/interactiveshell.py", line 321, in prompt_for_code
    pre_run=self.pre_prompt, reset_current_buffer=True)
  File "/Users/hdara/src/python-prompt-toolkit/prompt_toolkit/interface.py", line 389, in run
    self.eventloop.run(self.input, self.create_eventloop_callbacks())
  File "/Users/hdara/src/python-prompt-toolkit/prompt_toolkit/eventloop/posix.py", line 154, in run
    t()
  File "/Users/hdara/src/python-prompt-toolkit/prompt_toolkit/eventloop/posix.py", line 82, in read_from_stdin
    inputstream.feed(data)
  File "/Users/hdara/src/python-prompt-toolkit/prompt_toolkit/terminal/vt100_input.py", line 380, in feed
    self._input_parser.send(c)
  File "/Users/hdara/src/python-prompt-toolkit/prompt_toolkit/terminal/vt100_input.py", line 299, in _input_parser_generator
    self._call_handler(match, prefix)
  File "/Users/hdara/src/python-prompt-toolkit/prompt_toolkit/terminal/vt100_input.py", line 332, in _call_handler
    self.feed_key_callback(KeyPress(key, insert_text))
  File "/Users/hdara/src/python-prompt-toolkit/prompt_toolkit/interface.py", line 1012, in feed_key
    cli.input_processor.process_keys()
  File "/Users/hdara/src/python-prompt-toolkit/prompt_toolkit/key_binding/input_processor.py", line 201, in process_keys
    self._process_coroutine.send(key_press)
  File "/Users/hdara/src/python-prompt-toolkit/prompt_toolkit/key_binding/input_processor.py", line 158, in _process
    self._call_handler(matches[-1], key_sequence=buffer)
  File "/Users/hdara/src/python-prompt-toolkit/prompt_toolkit/key_binding/input_processor.py", line 228, in _call_handler
    handler.call(event)
  File "/Users/hdara/src/python-prompt-toolkit/prompt_toolkit/key_binding/registry.py", line 31, in call
    return self.handler(event)
  File "/Users/hdara/src/python-prompt-toolkit/prompt_toolkit/key_binding/bindings/basic.py", line 261, in _
    deleted = event.current_buffer.delete_before_cursor(count=event.arg)
  File "/Users/hdara/src/python-prompt-toolkit/prompt_toolkit/buffer.py", line 568, in delete_before_cursor
    assert count >= 0
AssertionError
```

**Comment by haridsv** [comment]
I am assuming this is not an iPython bug, but otherwise please let me know and I will close this and open one with iPython.

**Comment by jonathanslenders** [comment]
This is definitely a prompt-toolkit bug! Thanks a lot for reporting, this has to be fixed asap.

**Comment by jonathanslenders** [comment]
This has been fixed: https://github.com/jonathanslenders/python-prompt-toolkit/commit/bd5a2dbe2e539a826aebe661a73ada0531ff36ea

However, the behaviour is apparently not yet exactly the same like readline. This needs to be improved.

**Comment by haridsv** [comment]
Yes, this change fixed the issue.

As for not behaving exactly like readline, I just read that `M-- C-k` should kill text back to the start of the line, so I just filed issue #347.

**Comment by jonathanslenders** [comment]
#347 has been fixed, so I close this one. Feel free to open again, if I'm missing something!
