### ISSUE TITLE
AssertionError from full screen tutorial code

### ISSUE THREAD

**Issue by tsvenson** [jonathanslenders/python-prompt-toolkit#349]
I'm trying to follow the full screen application tutorial on http://python-prompt-toolkit.readthedocs.io/en/stable/pages/full_screen_apps.html, but get the following error on just the first code example:
```
Traceback (most recent call last):
  File "mco.py", line 13, in <module>
    cli = CommandLineInterface(application=application)
  File "/home/tsvenson/.virtualenvs/orson/lib/python3.4/site-packages/prompt_toolkit/interface.py", line 69, in __init__
    assert isinstance(eventloop, EventLoop)
AssertionError
```

List of venv-modules:
```
mysql-connector-python (2.1.3)
pip (7.1.2)
prompt-toolkit (1.0.3)
setuptools (18.2)
six (1.10.0)
wcwidth (0.1.7)
wheel (0.24.0)
```

This is on Ubuntu 14.04 LTS

**Comment by jonathanslenders** [comment]
Hi @tsvenson,

The error message should be improved, and there is indeed a bug in the documentation.
the 'eventloop' argument became required. I already made some changes: https://github.com/jonathanslenders/python-prompt-toolkit/commit/98161ba5650dc3d294c9ba7bb906bda4d09957ac

But this page of documentation needs to be rewritten. Documentation for creating full screen applications is also lacking a bit. This will get more of my focus in the coming year.

Jonathan

**Comment by tsvenson** [comment]
Thanks for quick reply Jonathan, and the pointer to the commit including the info I need to get forward on my project.

If you are interested, I can help with the work on improving the full screen application documentation. I'm new to Python, but the project I am working on will utilizing a console based UI as a backend for system administration amongst other things. Thus, I am able to give you a fresh pair of newbie eyes if needed.

**Comment by jonathanslenders** [comment]
Hi @tsvenson,

Thanks for proposing this! I really apprecatiate it, documentation is very important.

However, some of the APIs will change, so don't wast too much of your time right now, documenting full screen applications. See: https://github.com/jonathanslenders/python-prompt-toolkit/issues/350
On the other hand, if you're willing to improve the documentation about "prompts", go ahead. That's going to be very useful.

Jonathan

**Comment by tsvenson** [comment]
Hi @jonathanslenders,

Very much like the plan outlined in #350 as those API changes will be incredible good improvements for the project I just started on.

Since, after research and comparison, I've opted to make Prompt Toolkit a core dependency my goal is to really learn it. However, I am new to Python and also rusty from a decade pretty much away from coding, even though it is beginning to come back. So, at the moment a lot of time goes to getting up to speed with Python, tons to learn before I feel _comfortable_. This includes getting to know Sphinx and Read the Docs.

That said, learning "prompts" with the goal to also try and improve the documentation sounds like an excellent plan for me. Just give me a few weeks and hopefully that will start to pay off.

/thomas
