### ISSUE TITLE
IndexError while making recursive function

### ISSUE THREAD

**Issue by pgy** [jonathanslenders/python-prompt-toolkit#37]
IndexError was thrown while typing the following:

    ➜  ~  ptpython --vi
    In [1]: def bez(cps, t):
        2.     if len(cps) < 2:                        
        3.         return cps[0]                           
        4.     p1 = bez(cps[0:
                            ^--- Exception happened here

Full output:

    ➜  ~  ptpython --vi
    In [1]: def bez(cps, t):
         2.     if len(cps) < 2:                        
         3.         return cps[0]                           
         4.     p1 = bez(Traceback (most recent call last):
      File "/usr/local/bin/ptpython", line 80, in <module>
        _run_repl()       all                        
      File "/usr/local/bin/ptpython", line 77, in _run_repl
        startup_paths=startup_paths, always_multiline=always_multiline)
      File "/usr/local/lib/python2.7/dist-packages/prompt_toolkit/contrib/repl.py",d
        cli.start_repl(startup_paths=startup_paths)
      File "/usr/local/lib/python2.7/dist-packages/prompt_toolkit/contrib/repl.py",l
        on_exit=AbortAction.RAISE_EXCEPTION)
      File "/usr/local/lib/python2.7/dist-packages/prompt_toolkit/__init__.py", lint
        self._redraw()
      File "/usr/local/lib/python2.7/dist-packages/prompt_toolkit/__init__.py", linw
        self.renderer.render(self)
      File "/usr/local/lib/python2.7/dist-packages/prompt_toolkit/renderer.py", linr
        output = self.render_to_str(cli)
      File "/usr/local/lib/python2.7/dist-packages/prompt_toolkit/renderer.py", linr
        self.layout.write_to_screen(cli, screen, height)
      File "/usr/local/lib/python2.7/dist-packages/prompt_toolkit/layout/__init__.pn
        t.write(cli, screen)z(cps, t)                                               
      File "/usr/local/lib/python2.7/dist-packages/prompt_toolkit/layout/toolbars.pe
        tokens = self.get_tokens(cli, width)
      File "/usr/local/lib/python2.7/dist-packages/prompt_toolkit/contrib/python_ins
        append((Signature, sig.full_name))
      File "/usr/local/lib/python2.7/dist-packages/jedi/api/classes.py", line 295, e
        path = [unicode(p) for p in self._path()]
      File "/usr/local/lib/python2.7/dist-packages/jedi/api/classes.py", line 170, h
        path.insert(0, par.name)
      File "/usr/local/lib/python2.7/dist-packages/jedi/api/interpreter.py", line 3_
        return getattr(self.parser_module, name)
      File "/usr/local/lib/python2.7/dist-packages/jedi/parser/fast.py", line 38, i_
        return getattr(self.parsers[0].module, name)
    IndexError: list index out of range

**Comment by jonathanslenders** [comment]
Hi all, closing this ticket because ``ptpython`` was removed from ``prompt-toolkit`` and got its own repository: https://github.com/jonathanslenders/ptpython/ . Further, the ``Jedi`` library for ``ptpython`` has been upgraded and we handle all known exceptions already. Let's create a new ticket if it happens again.
