### ISSUE TITLE
BrokenPipeError/OSError

### ISSUE THREAD

**Issue by laerus** [jonathanslenders/python-prompt-toolkit#391]
one out of 3-4 times on [xonsh](https://github.com/xonsh/xonsh) startup with ptk i'm getting 

```
Traceback (most recent call last):
  File "/home/laerus/projects/xonsh/xonsh/ptk/shortcuts.py", line 108, in prompt
    document = cli.run(reset_current_buffer=False)
  File "/home/laerus/.local/lib/python3.5/site-packages/prompt_toolkit/interface.py", line 389, in run
    self.eventloop.run(self.input, self.create_eventloop_callbacks())
  File "/home/laerus/.local/lib/python3.5/site-packages/prompt_toolkit/eventloop/posix.py", line 153, in run
    t()
  File "/home/laerus/.local/lib/python3.5/site-packages/prompt_toolkit/eventloop/posix.py", line 81, in read_from_stdin
    inputstream.feed(data)
  File "/home/laerus/.local/lib/python3.5/site-packages/prompt_toolkit/terminal/vt100_input.py", line 390, in feed
    self._input_parser.send(c)
  File "/home/laerus/.local/lib/python3.5/site-packages/prompt_toolkit/terminal/vt100_input.py", line 299, in _input_parser_generator
    self._call_handler(match, prefix)
  File "/home/laerus/.local/lib/python3.5/site-packages/prompt_toolkit/terminal/vt100_input.py", line 332, in _call_handler
    self.feed_key_callback(KeyPress(key, insert_text))
  File "/home/laerus/.local/lib/python3.5/site-packages/prompt_toolkit/interface.py", line 1019, in feed_key
    cli.input_processor.process_keys()
  File "/home/laerus/.local/lib/python3.5/site-packages/prompt_toolkit/key_binding/input_processor.py", line 209, in process_keys
    cli.invalidate()
  File "/home/laerus/.local/lib/python3.5/site-packages/prompt_toolkit/interface.py", line 333, in invalidate
    self.eventloop.call_from_executor(redraw, _max_postpone_until=_max_postpone_until)
  File "/home/laerus/.local/lib/python3.5/site-packages/prompt_toolkit/eventloop/posix.py", line 236, in call_from_executor
    os.write(self._schedule_pipe[1], b'x')
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/laerus/.local/bin/xonsh", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/laerus/projects/xonsh/scripts/xonsh", line 3, in <module>
    main()
  File "/home/laerus/projects/xonsh/xonsh/main.py", line 221, in main
    shell.shell.cmdloop()
  File "/home/laerus/projects/xonsh/xonsh/ptk/shell.py", line 114, in cmdloop
    line = self.singleline(auto_suggest=auto_suggest)
  File "/home/laerus/projects/xonsh/xonsh/ptk/shell.py", line 83, in singleline
    line = self.prompter.prompt(**prompt_args)
  File "/home/laerus/projects/xonsh/xonsh/ptk/shortcuts.py", line 113, in prompt
    eventloop.close()
  File "/home/laerus/.local/lib/python3.5/site-packages/prompt_toolkit/eventloop/posix.py", line 252, in close
    os.close(schedule_pipe[0])
OSError: [Errno 9] Bad file descriptor
```

[xonsh issue  #1710](https://github.com/xonsh/xonsh/issues/1710#issue-176180691)

any idea why this is happening?

on latest PyPI version `prompt-toolkit==1.0.7`

**Comment by jonathanslenders** [comment]
Hi @laerus,

Thank you for reporting this issue! That sounds like a bug.
Which OS, Python version and terminal application are you using?
I'd like to be able to reproduce this.

**Comment by laerus** [comment]
hey @jonathanslenders, i'm on debian-testing, python3.5.2 and terminator.

**Comment by jonathanslenders** [comment]
Hi @laerus,

So far, I have not been able to reproduce this.
However, it could be that the following commit will fix it: https://github.com/jonathanslenders/python-prompt-toolkit/commit/144f9c28cf54eaee437197c5dde5b2c6dc7ae385 There was definitely a race condition.
Can you have a try?

**Comment by laerus** [comment]
i cannot reproduce this anymore, thanks @jonathanslenders !
