### ISSUE TITLE
the hello world demo works in ubuntu but not work in windows

### ISSUE THREAD

**Issue by yonghuming** [jonathanslenders/python-prompt-toolkit#401]
from __future__ import unicode_literals
from prompt_toolkit import prompt

text = prompt('Give me some input: ')
print('You said: %s' % text)

`Traceback (most recent call last):
  File "D:\coding\pty\pty.py", line 4, in <module>
    text = prompt('Give me some input: ')
  File "C:\Python27\lib\site-packages\prompt_toolkit\shortcuts.py", line 544, in prompt
    eventloop=eventloop)
  File "C:\Python27\lib\site-packages\prompt_toolkit\shortcuts.py", line 572, in run_application
    output=create_output(true_color=true_color))
  File "C:\Python27\lib\site-packages\prompt_toolkit\shortcuts.py", line 116, in create_output
    return Win32Output(stdout)
  File "C:\Python27\lib\site-packages\prompt_toolkit\terminal\win32_output.py", line 80, in __init__
    info = self.get_win32_screen_buffer_info()
  File "C:\Python27\lib\site-packages\prompt_toolkit\terminal\win32_output.py", line 50, in __init__
    xterm = 'xterm' in os.environ.get('TERM')
TypeError: argument of type 'NoneType' is not iterable`

**Comment by stephenrauch** [comment]
Was this fixed here?: https://github.com/jonathanslenders/python-prompt-toolkit/commit/99fa7fae61c9b4ed9767ead3b4f9b1318cfa875d

**Comment by jonathanslenders** [comment]
That looks indeed like the fix.

@yonghuming, I'm closing the issue, because it should be fixed in the latest prompt_toolkit release. Feel free to open the issue again, if you still experience any issues.
