### ISSUE TITLE
RuntimeError when autocompleting Flask-SQLAlchemy queries

### ISSUE THREAD

**Issue by jpvanhal** [jonathanslenders/python-prompt-toolkit#402]
We're using ptpython with [Flask-Konch](https://github.com/sloria/flask-konch), and noticed that the autocompletion crashes whenever ptpython tries to autocomplete Flask-SQLAlchemy queries. 

Below is the minimal code to reproduce the issue in ptpython shell:

``` python
>>> from flask import Flask
>>> from flask_sqlalchemy import SQLAlchemy
>>>
>>> app = Flask(__name__)
>>> db = SQLAlchemy()
>>> db.init_app(app)
>>>
>>> class User(db.Model):
...     __tablename__ = 'users'
...      id = db.Column(db.Integer, primary_key=True)
...      email = db.Column(db.Text)

>>> User.query.filter_by(eException in thread Thread-168:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/janne/.virtualenvs/python-prompt-toolkit/lib/python2.7/site-packages/prompt_toolkit/interface.py", line 836, in run [F2] Menu - CPython 2.7.12
    completions = list(buffer.completer.get_completions(document, complete_event))
  File "/Users/janne/.virtualenvs/python-prompt-toolkit/lib/python2.7/site-packages/ptpython/completer.py", line 127, in get_completions
    completions = script.completions()
  File "/Users/janne/.virtualenvs/python-prompt-toolkit/lib/python2.7/site-packages/jedi/api/__init__.py", line 192, in completions
    for call_sig in self.call_signatures():
  File "/Users/janne/.virtualenvs/python-prompt-toolkit/lib/python2.7/site-packages/jedi/api/__init__.py", line 521, in call_signatures
    self.source, self._pos)
  File "/Users/janne/.virtualenvs/python-prompt-toolkit/lib/python2.7/site-packages/jedi/cache.py", line 93, in wrapper
    value = next(generator)
  File "/Users/janne/.virtualenvs/python-prompt-toolkit/lib/python2.7/site-packages/jedi/cache.py", line 115, in cache_call_signatures
    yield evaluator.eval_element(call)
  File "/Users/janne/.virtualenvs/python-prompt-toolkit/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/janne/.virtualenvs/python-prompt-toolkit/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 187, in eval_element
    types = self.eval_trailer(types, trailer)
  File "/Users/janne/.virtualenvs/python-prompt-toolkit/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 257, in eval_trailer
    new_types += self.find_types(typ, node)
  File "/Users/janne/.virtualenvs/python-prompt-toolkit/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 120, in find_types
    return f.find(scopes, search_global)
  File "/Users/janne/.virtualenvs/python-prompt-toolkit/lib/python2.7/site-packages/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/Users/janne/.virtualenvs/python-prompt-toolkit/lib/python2.7/site-packages/jedi/evaluate/finder.py", line 86, in find
    names = self.filter_name(scopes)
  File "/Users/janne/.virtualenvs/python-prompt-toolkit/lib/python2.7/site-packages/jedi/evaluate/finder.py", line 177, in filter_name
    names = self.names_dict_lookup(names_dict, position)
  File "/Users/janne/.virtualenvs/python-prompt-toolkit/lib/python2.7/site-packages/jedi/evaluate/finder.py", line 119, in names_dict_lookup
    names = names_dict[search_str]
  File "/Users/janne/.virtualenvs/python-prompt-toolkit/lib/python2.7/site-packages/jedi/cache.py", line 160, in wrapper
    result = method(self, *args, **kwargs)
  File "/Users/janne/.virtualenvs/python-prompt-toolkit/lib/python2.7/site-packages/jedi/evaluate/compiled/__init__.py", line 263, in __getitem__
    getattr(self._compiled_obj.obj, name)
  File "/Users/janne/.virtualenvs/python-prompt-toolkit/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py", line 500, in __get__
    return type.query_class(mapper, session=self.sa.session())
  File "/Users/janne/.virtualenvs/python-prompt-toolkit/lib/python2.7/site-packages/sqlalchemy/orm/scoping.py", line 78, in __call__
    return self.registry()
  File "/Users/janne/.virtualenvs/python-prompt-toolkit/lib/python2.7/site-packages/sqlalchemy/util/_collections.py", line 990, in __call__
    return self.registry.setdefault(key, self.createfunc())
  File "/Users/janne/.virtualenvs/python-prompt-toolkit/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py", line 771, in create_session
    return SignallingSession(self, **options)
  File "/Users/janne/.virtualenvs/python-prompt-toolkit/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py", line 153, in __init__
    self.app = app = db.get_app()
  File "/Users/janne/.virtualenvs/python-prompt-toolkit/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py", line 922, in get_app
    raise RuntimeError('application not registered on db '
RuntimeError: application not registered on db instance and no application bound to current context
```

The same thing happens also even if there's an application context:

``` python
>>> ctx = app.app_context()
>>> ctx.push()
>>> User.query.filter_by(eException in thread Thread-407:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/janne/.virtualenvs/python-prompt-toolkit/lib/python2.7/site-packages/prompt_toolkit/interface.py", line 836, in run [F2] Menu - CPython 2.7.12
    completions = list(buffer.completer.get_completions(document, complete_event))
  File "/Users/janne/.virtualenvs/python-prompt-toolkit/lib/python2.7/site-packages/ptpython/completer.py", line 127, in get_completions
    completions = script.completions()
  File "/Users/janne/.virtualenvs/python-prompt-toolkit/lib/python2.7/site-packages/jedi/api/__init__.py", line 192, in completions
    for call_sig in self.call_signatures():
  File "/Users/janne/.virtualenvs/python-prompt-toolkit/lib/python2.7/site-packages/jedi/api/__init__.py", line 521, in call_signatures
    self.source, self._pos)
  File "/Users/janne/.virtualenvs/python-prompt-toolkit/lib/python2.7/site-packages/jedi/cache.py", line 93, in wrapper
    value = next(generator)
  File "/Users/janne/.virtualenvs/python-prompt-toolkit/lib/python2.7/site-packages/jedi/cache.py", line 115, in cache_call_signatures
    yield evaluator.eval_element(call)
  File "/Users/janne/.virtualenvs/python-prompt-toolkit/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/janne/.virtualenvs/python-prompt-toolkit/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 187, in eval_element
    types = self.eval_trailer(types, trailer)
  File "/Users/janne/.virtualenvs/python-prompt-toolkit/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 257, in eval_trailer
    new_types += self.find_types(typ, node)
  File "/Users/janne/.virtualenvs/python-prompt-toolkit/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 120, in find_types
    return f.find(scopes, search_global)
  File "/Users/janne/.virtualenvs/python-prompt-toolkit/lib/python2.7/site-packages/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/Users/janne/.virtualenvs/python-prompt-toolkit/lib/python2.7/site-packages/jedi/evaluate/finder.py", line 86, in find
    names = self.filter_name(scopes)
  File "/Users/janne/.virtualenvs/python-prompt-toolkit/lib/python2.7/site-packages/jedi/evaluate/finder.py", line 177, in filter_name
    names = self.names_dict_lookup(names_dict, position)
  File "/Users/janne/.virtualenvs/python-prompt-toolkit/lib/python2.7/site-packages/jedi/evaluate/finder.py", line 119, in names_dict_lookup
    names = names_dict[search_str]
  File "/Users/janne/.virtualenvs/python-prompt-toolkit/lib/python2.7/site-packages/jedi/cache.py", line 160, in wrapper
    result = method(self, *args, **kwargs)
  File "/Users/janne/.virtualenvs/python-prompt-toolkit/lib/python2.7/site-packages/jedi/evaluate/compiled/__init__.py", line 263, in __getitem__
    getattr(self._compiled_obj.obj, name)
  File "/Users/janne/.virtualenvs/python-prompt-toolkit/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py", line 500, in __get__
    return type.query_class(mapper, session=self.sa.session())
  File "/Users/janne/.virtualenvs/python-prompt-toolkit/lib/python2.7/site-packages/sqlalchemy/orm/scoping.py", line 78, in __call__
    return self.registry()
  File "/Users/janne/.virtualenvs/python-prompt-toolkit/lib/python2.7/site-packages/sqlalchemy/util/_collections.py", line 990, in __call__
    return self.registry.setdefault(key, self.createfunc())
  File "/Users/janne/.virtualenvs/python-prompt-toolkit/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py", line 771, in create_session
    return SignallingSession(self, **options)
  File "/Users/janne/.virtualenvs/python-prompt-toolkit/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py", line 153, in __init__
    self.app = app = db.get_app()
  File "/Users/janne/.virtualenvs/python-prompt-toolkit/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py", line 922, in get_app
    raise RuntimeError('application not registered on db '
RuntimeError: application not registered on db instance and no application bound to current context
```

That's probably because python-prompt-toolkit seems to use a different thread for the autocompletion, and Flask's app context is bound to the thread it was created in.

**Comment by jonathanslenders** [comment]
That's a bug. Thanks for reporting!
I don't know whether it's Jedi that should handle it, or Flask, but it should not crash here in any case.

Prompt_toolkit uses indeed a different thread for autocompletion. This is required in order to make the UI responsive. (Jedi is not fast enough to execute it on every single key stroke.)

**Comment by jpvanhal** [comment]
> That's a bug. Thanks for reporting!
> I don't know whether it's Jedi that should handle it, or Flask, but it should not crash here in any case.

Thanks for the response! I reported the issue to Jedi (davidhalter/jedi#785).

> Prompt_toolkit uses indeed a different thread for autocompletion. This is required in order to make the UI responsive. (Jedi is not fast enough to execute it on every single key stroke.)

Alright. I guess that just means that prompt_toolkit won't be able to provide autocompletion in scenarios that depend on a certain thread.

**Comment by jonathanslenders** [comment]
> Alright. I guess that just means that prompt_toolkit won't be able to provide autocompletion in scenarios that depend on a certain thread.

That will be difficult indeed. I'm not sure what we can do about that right now. Maybe at some point, Jedi could support plugins that handle auto completion for certain libraries.

**Comment by jonathanslenders** [comment]
Closing this, as it has been fixed in Jedi.
