### ISSUE TITLE
NoConsoleScreenBufferError when executing the hello world example in Windows.

### ISSUE THREAD

**Issue by jonmon6691** [jonathanslenders/python-prompt-toolkit#406]
Running on python 3.4, I was having trouble with django's `manage.py shell` command. I've narrowed it down to the prompt_toolkit module and can demonstrate the problem with this simple code:

```python
>>> import prompt_toolkit
>>> prompt_toolkit.prompt("Hi")
Hi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python34\lib\site-packages\prompt_toolkit\shortcuts.py", line 545, in prompt
    eventloop=eventloop)
  File "C:\Python34\lib\site-packages\prompt_toolkit\shortcuts.py", line 626, in run_application
    result = cli.run(reset_current_buffer=False)
  File "C:\Python34\lib\site-packages\prompt_toolkit\interface.py", line 391, in run
    self.renderer.request_absolute_cursor_position()
  File "C:\Python34\lib\site-packages\prompt_toolkit\renderer.py", line 343, in request_absolute_cursor_position
    self._min_available_height = self.output.get_rows_below_cursor_position()
  File "C:\Python34\lib\site-packages\prompt_toolkit\terminal\win32_output.py", line 287, in get_rows_below_cursor_position
    info = self.get_win32_screen_buffer_info()
  File "C:\Python34\lib\site-packages\prompt_toolkit\terminal\win32_output.py", line 150, in get_win32_screen_buffer_info
    raise NoConsoleScreenBufferError
prompt_toolkit.terminal.win32_output.NoConsoleScreenBufferError: No Windows console found. Are you running cmd.exe?
>>>
```

Let me know what other information I can provide

**Comment by jonmon6691** [comment]
I tried enabling the logging by changing `_DEBUG_RENDER_OUTPUT` to `True`and ran into another bug, `Win32Output` attempts to write to `self.LOG` before it's opened at the end of `__init__`. Moving the lines that open and define `self.LOG` above the call to `get_win32_screen_buffer_info` fixes this. Strangely, the original example no longer fails, and the log file looks like this:
```python
Python 3.4.2 (v3.4.2:ab2c023a9432, Oct  6 2014, 22:16:31) [MSC v.1600 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import prompt_toolkit as p
>>> p.prompt("Hi")
Hif
'f'
>>> ^Z

```

```
'GetConsoleScreenBufferInfo'
     76, <cparam 'P' (0000000003AC5420)>
     <class 'int'>, <class 'CArgObject'>
'GetConsoleScreenBufferInfo'
     76, <cparam 'P' (0000000003AC54A0)>
     <class 'int'>, <class 'CArgObject'>
'SetConsoleWindowInfo'
     76, True, <cparam 'P' (00000000046A5D90)>
     <class 'int'>, <class 'bool'>, <class 'CArgObject'>
'GetConsoleScreenBufferInfo'
     76, <cparam 'P' (0000000003AC5660)>
     <class 'int'>, <class 'CArgObject'>
'GetConsoleScreenBufferInfo'
     76, <cparam 'P' (0000000003AC5420)>
     <class 'int'>, <class 'CArgObject'>
'SetConsoleTextAttribute'
     76, 7
     <class 'int'>, <class 'int'>
'SetConsoleTextAttribute'
     76, 7
     <class 'int'>, <class 'int'>
'GetConsoleScreenBufferInfo'
     76, <cparam 'P' (0000000003AC5680)>
     <class 'int'>, <class 'CArgObject'>
'FillConsoleOutputCharacterA'
     76, c_char(b' '), c_ulong(103), c_long(19595264), <cparam 'P' (00000000046A5E10)>
     <class 'int'>, <class 'ctypes.c_char'>, <class 'ctypes.c_ulong'>, <class 'ctypes.c_long'>, <class 'CArgObject'>
'GetConsoleScreenBufferInfo'
     76, <cparam 'P' (0000000003AC5380)>
     <class 'int'>, <class 'CArgObject'>
'FillConsoleOutputAttribute'
     76, 7, 103, c_long(19595264), <cparam 'P' (00000000046A5E10)>
     <class 'int'>, <class 'int'>, <class 'int'>, <class 'ctypes.c_long'>, <class 'CArgObject'>
'SetConsoleTextAttribute'
     76, 7
     <class 'int'>, <class 'int'>
'Hi'
'GetConsoleScreenBufferInfo'
     76, <cparam 'P' (0000000003AC50E0)>
     <class 'int'>, <class 'CArgObject'>
'SetConsoleCursorPosition'
     76, c_long(19595264)
     <class 'int'>, <class 'ctypes.c_long'>
'GetConsoleScreenBufferInfo'
     76, <cparam 'P' (0000000003AC5460)>
     <class 'int'>, <class 'CArgObject'>
'SetConsoleCursorPosition'
     76, c_long(19595266)
     <class 'int'>, <class 'ctypes.c_long'>
'SetConsoleTextAttribute'
     76, 7
     <class 'int'>, <class 'int'>
'GetConsoleScreenBufferInfo'
     76, <cparam 'P' (0000000003AC55E0)>
     <class 'int'>, <class 'CArgObject'>
'SetConsoleTextAttribute'
     76, 7
     <class 'int'>, <class 'int'>
'f'
'SetConsoleTextAttribute'
     76, 7
     <class 'int'>, <class 'int'>
'GetConsoleScreenBufferInfo'
     76, <cparam 'P' (0000000003AC5480)>
     <class 'int'>, <class 'CArgObject'>
'GetConsoleScreenBufferInfo'
     76, <cparam 'P' (0000000003AC5640)>
     <class 'int'>, <class 'CArgObject'>
'SetConsoleCursorPosition'
     76, c_long(19595264)
     <class 'int'>, <class 'ctypes.c_long'>
'SetConsoleTextAttribute'
     76, 7
     <class 'int'>, <class 'int'>
'GetConsoleScreenBufferInfo'
     76, <cparam 'P' (0000000003AC50E0)>
     <class 'int'>, <class 'CArgObject'>
'FillConsoleOutputCharacterA'
     76, c_char(b' '), c_ulong(103), c_long(19595264), <cparam 'P' (00000000046A5E10)>
     <class 'int'>, <class 'ctypes.c_char'>, <class 'ctypes.c_ulong'>, <class 'ctypes.c_long'>, <class 'CArgObject'>
'GetConsoleScreenBufferInfo'
     76, <cparam 'P' (0000000003AC5100)>
     <class 'int'>, <class 'CArgObject'>
'FillConsoleOutputAttribute'
     76, 7, 103, c_long(19595264), <cparam 'P' (00000000046A5E10)>
     <class 'int'>, <class 'int'>, <class 'int'>, <class 'ctypes.c_long'>, <class 'CArgObject'>
'SetConsoleTextAttribute'
     76, 7
     <class 'int'>, <class 'int'>
'Hi'
'SetConsoleTextAttribute'
     76, 7
     <class 'int'>, <class 'int'>
'f'
'GetConsoleScreenBufferInfo'
     76, <cparam 'P' (0000000003AC5620)>
     <class 'int'>, <class 'CArgObject'>
'SetConsoleCursorPosition'
     76, c_long(19595264)
     <class 'int'>, <class 'ctypes.c_long'>
'SetConsoleTextAttribute'
     76, 7
     <class 'int'>, <class 'int'>
'\r\n'
'GetConsoleScreenBufferInfo'
     76, <cparam 'P' (0000000003AC5640)>
     <class 'int'>, <class 'CArgObject'>
'SetConsoleCursorPosition'
     76, c_long(19595264)
     <class 'int'>, <class 'ctypes.c_long'>
'GetConsoleScreenBufferInfo'
     76, <cparam 'P' (0000000003AC51E0)>
     <class 'int'>, <class 'CArgObject'>
'FillConsoleOutputCharacterA'
     76, c_char(b' '), c_ulong(103), c_long(19595264), <cparam 'P' (00000000046A5790)>
     <class 'int'>, <class 'ctypes.c_char'>, <class 'ctypes.c_ulong'>, <class 'ctypes.c_long'>, <class 'CArgObject'>
'GetConsoleScreenBufferInfo'
     76, <cparam 'P' (0000000003AC51C0)>
     <class 'int'>, <class 'CArgObject'>
'FillConsoleOutputAttribute'
     76, 7, 103, c_long(19595264), <cparam 'P' (00000000046A5790)>
     <class 'int'>, <class 'int'>, <class 'int'>, <class 'ctypes.c_long'>, <class 'CArgObject'>
'SetConsoleTextAttribute'
     76, 7
     <class 'int'>, <class 'int'>
```

The debug logging must have a side-effect of some kind that is preventing the prompt call from failing. I think if we find that, we'll have a fix.

**Comment by stephenrauch** [comment]
Works for me...

```
C:\Python34>python
Python 3.4.4 (v3.4.4:737efcadf5a6, Dec 20 2015, 19:28:18) [MSC v.1600 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import prompt_toolkit as p
>>> p.prompt("Hi")
Hi
''
>>>
```

**Comment by jonathanslenders** [comment]
@jonmon6691 Are you executing this code from inside PyCharm or Idle? Or does it run in cmd.exe?

**Comment by jonmon6691** [comment]
It was run within cmd.exe

**Comment by zhizunbao84** [comment]
i get that error, and i also run within cmd.exe

**Comment by erm3nda** [comment]
Same for me, first time that i got this kind of error. Ouput differs from `ipython` and `jupyter console` but the final error is the same. The notebook works.

Error: 
```
line 150, in get_win32_screen_buffer_info
    raise NoConsoleScreenBufferError
NoConsoleScreenBufferError: No Windows console found. Are you running cmd.exe?
```

I've paste the whole cmd content here: http://pastebin.com/RW5AgyeL

**Comment by jonathanslenders** [comment]
@erm3nda: Which Windows version are you using? And is it 64 bit or 32 bit?

So  far I still have not been able to reproduce it, but it seems that for some people it consistently fails, while for most people everything works consistently fine...

**Comment by erm3nda** [comment]
@jonathanslenders 

This is under W10 x64, Python 2.7.1x, and i did launch it from cmd from admin account.
I'll try later using a regular user, maybe something changes, but i don't expect anything to run bad from admin... usually it's the opposite, and also changed cwd to User folder but didn't change anything.

I can try whatever you suggest. I don't really need ipython over this laptop with Windows, but i am also curious to know which kind of shit is under the hood :-) and wondering it's Windows fault :-)

Regards

**Comment by stephenrauch** [comment]
@erm3nda 

From the pastebin:

``` Python 2.7 (r27:82525, Jul  4 2010, 07:43:08) [MSC v.1500 64 bit (AMD64)] ```

Is this really 2.7.0?  mine says:

``` Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)] on win32 ```

Mine is a newer, but is also 32bit not 64 bit.  You and the OP are using 64 bit.

**Comment by erm3nda** [comment]
Seems i was wrong. The current output is 2.7... i think i downloaded the 2.7.10, but seems no.

```
Microsoft Windows [Versión 6.3.9600]
(c) 2013 Microsoft Corporation. Todos los derechos reservados.

C:\Windows\System32>python
Python 2.7 (r27:82525, Jul  4 2010, 07:43:08) [MSC v.1500 64 bit (AMD64)] on win
32
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

**Comment by jonathanslenders** [comment]
I have a possible solution. See: https://github.com/ipython/ipython/issues/10070#issuecomment-269557351 . It's super weird...

**Comment by JumpsPumps** [comment]
Hi @jonathanslenders,
I am facing this issue while running the python script from pyCharm. Not happening when directly ran from cmd.

**Comment by GuardianCosmos** [comment]
@jonathanslenders @stephenrauch do we know if the patch will still work with toolkit version 2? and would the implementation be the same?

**Comment by mahadi** [comment]
I just saw, that you can check "Emulate terminal in output console" in your run/debug configuration to fix this error in PyCharm. For me this works.

![image](https://user-images.githubusercontent.com/124618/56195189-c3bcb180-6034-11e9-8073-b4e33b5f75d4.png)

**Comment by MagicRedDeer** [comment]
I have compiled a python 2.7.11 with MSVC1900 (Platform v140) for some of my needs. I am unable to run IPython in it on windows 10 due to this. 

FYI At the moment, I am okay with using IPython 4.2.1 until this bug is addressed.

**Comment by sailfish009** [comment]
i am using msys2 with python,  below command works for mingw64:

```
// msys2 shell
$ pacman -S winpty
$ winpty python
```

**Comment by pawamoy** [comment]
> sure that i'm running cmd.exe, what else i'm i supposed to do on Windows?

Use git-bash/powershell within Windows Terminal :D ?

**Comment by sjc-iii** [comment]
Hi...

Just starting to learn python in pycharm...  running this:

```
> from prompt_toolkit import prompt
user_input = prompt('>')

while user_input != 'quit':
    user_input = prompt('>')   
print(user_input)
```

> I get Traceback (most recent call last):
  File "C:\Users\TheChamberlins\Documents\PythonScripts\SourceControl\sandbox\sjcrepl.py", line 13, in <module>
    user_input = prompt('>',
  File "C:\Users\TheChamberlins\anaconda3\lib\site-packages\prompt_toolkit\shortcuts\prompt.py", line 1395, in prompt
    session: PromptSession[str] = PromptSession(history=history)
  File "C:\Users\TheChamberlins\anaconda3\lib\site-packages\prompt_toolkit\shortcuts\prompt.py", line 468, in __init__
    self.app = self._create_application(editing_mode, erase_when_done)
  File "C:\Users\TheChamberlins\anaconda3\lib\site-packages\prompt_toolkit\shortcuts\prompt.py", line 719, in _create_application
    application: Application[_T] = Application(
  File "C:\Users\TheChamberlins\anaconda3\lib\site-packages\prompt_toolkit\application\application.py", line 277, in __init__
    self.output = output or session.output
  File "C:\Users\TheChamberlins\anaconda3\lib\site-packages\prompt_toolkit\application\current.py", line 70, in output
    self._output = create_output()
  File "C:\Users\TheChamberlins\anaconda3\lib\site-packages\prompt_toolkit\output\defaults.py", line 73, in create_output
    return Win32Output(stdout, default_color_depth=color_depth_from_env)
  File "C:\Users\TheChamberlins\anaconda3\lib\site-packages\prompt_toolkit\output\win32.py", line 118, in __init__
    info = self.get_win32_screen_buffer_info()
  File "C:\Users\TheChamberlins\anaconda3\lib\site-packages\prompt_toolkit\output\win32.py", line 224, in get_win32_screen_buffer_info
    raise NoConsoleScreenBufferError
prompt_toolkit.output.win32.NoConsoleScreenBufferError: No Windows console found. Are you running cmd.exe?

When I do the (Run->Edit Configurations->execution->emulate terminal)   I don't get the error, but the terminal emulator doesn't seem to do line returns correctly... (when it reads a line, the cursor just drops to the next line at the same column (as opposed to doing a real carriage return)... so after a while the cursor marches to the right side of my screen.

Runs fine from cmd (which is what I'm doing now)... but it sure would be great to get this running in a pycharm console.
It seems like this has been around for a while and when it works (for some people) it works consistently, when it doesn't ... it doesn't.

Any advice?

--------------------------------------------------------------

Windows 10.

PyCharm 2022.2 (Community Edition)
Build #PC-222.3345.131, built on July 27, 2022
Runtime version: 17.0.3+7-b469.32 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2042M
Cores: 16

Python: 3.9.12.

**Comment by sjc-iii** [comment]
Got the latest pycharm patch... it fixed my terminal emulator problem (thank you thank you).

If there is any info I can give you guys relative to the base problem that would be useful?

**Comment by sk-keeper** [comment]
Is there any reason that `create_output` method does not check for tty on Windows as it does for Posix platforms?
https://github.com/prompt-toolkit/python-prompt-toolkit/blob/465ab02854763fafc0099a2e38a56328c1cb0625/src/prompt_toolkit/output/defaults.py#L94

It looks like `PlainTextOutput` is never created on Windows by the library. As a result apps that do `print_formatted_text` crash when `stdout` is redirected to a file.
