### ISSUE TITLE
UnicodeDecodeError on OpenBSD

### ISSUE THREAD

**Issue by vext01** [jonathanslenders/python-prompt-toolkit#43]
Hi,

I installed prompt-toolkit from pip on OpenBSD to try out ptipython. It's awesome. Nice work!

There is however an annoying bug. If i start a fresh ptipython and type 'import s' the following happens:

```
In [1]: import sException in thread Thread-8:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/home/edd/.local/lib/python2.7/site-packages/prompt_toolkit/__init__.pyn
    callback()
  File "/home/edd/.local/lib/python2.7/site-packages/prompt_toolkit/__init__.pyn
    completions = list(line.completer.get_completions(document))
  File "/home/edd/.local/lib/python2.7/site-packages/prompt_toolkit/contrib/ipys
    for c in super(IPythonCompleter, self).get_completions(document):
  File "/home/edd/.local/lib/python2.7/site-packages/prompt_toolkit/contrib/pyts
    completions = script.completions()
  File "/home/edd/.local/lib/python2.7/site-packages/jedi/api/__init__.py", lins
    completions = get_completions(user_stmt, b)
  File "/home/edd/.local/lib/python2.7/site-packages/jedi/api/__init__.py", lins
    return self._simple_complete(path, like)
  File "/home/edd/.local/lib/python2.7/site-packages/jedi/api/__init__.py", line
    return super(Interpreter, self)._simple_complete(path, like)
  File "/home/edd/.local/lib/python2.7/site-packages/jedi/api/__init__.py", line
    names = s.get_defined_names(on_import_stmt=True)
  File "/home/edd/.local/lib/python2.7/site-packages/jedi/evaluate/imports.py",s
    names += self._get_module_names([path])
  File "/home/edd/.local/lib/python2.7/site-packages/jedi/evaluate/imports.py",s
    for module_loader, name, is_pkg in pkgutil.iter_modules(search_path):
  File "/usr/local/lib/python2.7/pkgutil.py", line 147, in iter_modules
    for name, ispkg in iter_importer_modules(i, prefix):
  File "/usr/local/lib/python2.7/pkgutil.py", line 202, in iter_modules
    filenames.sort()  # handle packages before same-named modules
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb0 in position 25: ordina)
```
Packages:

```
$ pkg_info | grep python-2
ipython-2.1.0p1     enhanced interactive Python shell
python-2.7.8        interpreted object-oriented programming language
```

Locale:

```
$ echo $LC_CTYPE
en_US.UTF-8
```

Could be a bug in Python on OpenBSD of course.

Any ideas?

**Comment by jonathanslenders** [comment]
Hi all, closing this ticket because ``ptpython`` was removed from ``prompt-toolkit`` and got its own repository: https://github.com/jonathanslenders/ptpython/ . Further, the ``Jedi`` library for ``ptpython`` has been upgraded and we handle all known exceptions already. Let's create a new ticket if it happens again.
