### ISSUE TITLE
IndexError

### ISSUE THREAD

**Issue by jonathanslenders** [jonathanslenders/python-prompt-toolkit#46]
Not sure if this was already fixed. (I'm creating a ticket, just not to forget about this.)

```python
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()DebtorSubscription
  File "/home/jonathan/git/prompt_toolkit/prompt_toolkit/eventloop/base.py", line 43, in run
    callback()
  File "/home/jonathan/git/prompt_toolkit/prompt_toolkit/__init__.py", line 399, in run
    completions = list(line.completer.get_completions(document))
  File "/home/jonathan/git/prompt_toolkit/prompt_toolkit/contrib/ipython.py", line 61, in get_completions
    for c in super(IPythonCompleter, self).get_completions(document):
  File "/home/jonathan/git/prompt_toolkit/prompt_toolkit/contrib/python_input.py", line 461, in get_completions
    script = get_jedi_script_from_document(document, self.get_locals(), self.get_globals())
  File "/home/jonathan/git/prompt_toolkit/prompt_toolkit/contrib/python_input.py", line 441, in get_jedi_script_from_document
    namespaces=[locals, globals])
  File "/home/jonathan/env/mobilevikings/local/lib/python2.7/site-packages/jedi/api/__init__.py", line 642, in __init__
    interpreter.create(self._evaluator, namespaces[0], self._parser.module())
  File "/home/jonathan/env/mobilevikings/local/lib/python2.7/site-packages/jedi/api/interpreter.py", line 107, in create
    for something in getattr(parser_module, attr_name):
  File "/home/jonathan/env/mobilevikings/local/lib/python2.7/site-packages/jedi/parser/fast.py", line 38, in __getattr__
    return getattr(self.parsers[0].module, name)
IndexError: list index out of range
```

**Comment by jonathanslenders** [comment]
Closing this. We upgraded to a new Jedi version.
