### ISSUE TITLE
`prompt_async` is blocking on windows

### ISSUE THREAD

**Issue by eric-wieser** [jonathanslenders/python-prompt-toolkit#505]
Consider the following:
```
import asyncio

from prompt_toolkit.shortcuts import prompt_async

async def spam():
	while True:
		print("hello");
		await asyncio.sleep(0.1);
		print("World");
		await asyncio.sleep(0.1);


async def my_coroutine():
    while True:
        result = await prompt_async('Say something: ', patch_stdout=True)
        print('You said: %s' % result)

loop = asyncio.get_event_loop()
loop.run_until_complete(asyncio.gather(my_coroutine(), spam()))
loop.close()
```

What I expect to happen: The prompt is pushed down by a continual stream of `Hello` and `World`

What actually happens: Each time I push a single character, an extra `Hello` or `World` is printed - the output does not advance while waiting for a single character.

**Comment by jonathanslenders** [comment]
Hi @eric-wieser,

Thank you for reporting! I think this is a windows-only issue. The way that stdin is read blocks the event loop. If I recall correctly, this was fixed on the 2.0 branch. Could you check that out. I believe that the code above is compatible with 2.0. (However, it'll still take some time for 2.0 to release.)

Thanks,
Jonathan

**Comment by eric-wieser** [comment]
Installing the 2.0 branch gives the following error:
```
Traceback (most recent call last):
  File "main.py", line 20, in <module>
    loop.run_until_complete(asyncio.gather(my_coroutine(), spam()))
  File "C:\Program Files\Python 3.5\lib\asyncio\base_events.py", line 342, in run_until_complete
    return future.result()
  File "C:\Program Files\Python 3.5\lib\asyncio\futures.py", line 274, in result
    raise self._exception
  File "C:\Program Files\Python 3.5\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(value)
  File "main.py", line 16, in my_coroutine
    result = await prompt_async('Say something: ')
  File "<string>", line 6, in prompt_async
NameError: name 'create_asyncio_event_loop' is not defined
```

**Comment by eric-wieser** [comment]
`eventloop.utils.AsyncioTimeout` is also missing, even though `'AsyncioTimeout' in `eventloop.utils.__all__`.

Are there no automated tests on the 2.0 branch to catch these things?

**Comment by jonathanslenders** [comment]
Hi @eric-wieser,
Can you check whether this is still the case with the 2.0.1 release?
If not, I can close this issue.
Thanks!

**Comment by BYK** [comment]
Tested this with the modernized version of the initial case:
```py
import asyncio
from prompt_toolkit import PromptSession
from prompt_toolkit.patch_stdout import patch_stdout

async def spam():
    while True:
        print("hello");
        await asyncio.sleep(0.1);
        print("World");
        await asyncio.sleep(0.1);


async def my_coroutine():
    session = PromptSession()
    while True:
        with patch_stdout():
            result = await session.prompt_async('Say something: ')
        print('You said: %s' % result)


loop = asyncio.get_event_loop()
loop.run_until_complete(asyncio.gather(my_coroutine(), spam()))
loop.close()
```

Seems to be working as expected (prompt line is continuously pushed down even when typing).
