### ISSUE TITLE
Cannot import name INPUT_TIMEOUT

### ISSUE THREAD

**Issue by lllama** [jonathanslenders/python-prompt-toolkit#522]
Running the `pager.py` example on the 2.0 branch gives me the following import error:

```
Traceback (most recent call last):
  File ".\pager.py", line 96, in <module>
    full_screen=True)
  File "c:\users\test\documents\development\python-prompt-toolkit\prompt_toolkit\application\application.py", line 217, in __init__
    self._running_in_terminal_f = get_event_loop().create_future()
  File "c:\users\test\documents\development\python-prompt-toolkit\prompt_toolkit\eventloop\defaults.py", line 61, in get_event_loop
    _loop = create_event_loop()
  File "c:\users\test\documents\development\python-prompt-toolkit\prompt_toolkit\eventloop\defaults.py", line 22, in create_event_loop
    from .win32 import Win32EventLoop
  File "c:\users\test\documents\development\python-prompt-toolkit\prompt_toolkit\eventloop\win32.py", line 8, in <module>
    from .base import EventLoop, INPUT_TIMEOUT
ImportError: cannot import name 'INPUT_TIMEOUT'
```

Looks like it's not actually in `base.py` but there is a `INPUT_TIMEOUT_MS` in `win32.py`, so I'm going to guess that this is an old import that's not been cleaned up.

**Comment by jonathanslenders** [comment]
That looks like a bug. Thanks for reporting!

**Comment by jonathanslenders** [comment]
Hi @lllama, this was fixed today. Can you try again?

**Comment by lllama** [comment]
Yep - that seems to have fixed it.
