### ISSUE TITLE
how to handle KeyboardInterrupt at 2.0

### ISSUE THREAD

**Issue by randy3k** [jonathanslenders/python-prompt-toolkit#533]
Consider this

```python
        prompt = Prompt()

        try:
            text = prompt.prompt("> ", enable_suspend=True)
        except:
            pass

        text = prompt.prompt("> ")
        print(text)
```

At the first prompt, I sent a `^C`. And at the second prompt, I typed `foo`. However, at the end of the application, it shows `Future exception was never retrieved`. It may be because the exception was never probably handled. How I should handle it correctly?

```
>
> foo
foo
Future exception was never retrieved
future: <prompt_toolkit.eventloop.future.Future object at 0x110e3c6a0>
Traceback (most recent call last):
  File "/Users/Randy/Dropbox/R/Role/role/application.py", line 15, in run
    text = prompt.prompt("> ", enable_suspend=True)
  File "/Users/Randy/Dropbox/R/Role/role/deps/prompt_toolkit/shortcuts/prompt.py", line 657, in prompt
    return run_sync()
  File "/Users/Randy/Dropbox/R/Role/role/deps/prompt_toolkit/shortcuts/prompt.py", line 641, in run_sync
    return self.app.run()
```

**Comment by randy3k** [comment]
May need sth like `prompt.reset`!?

**Comment by jonathanslenders** [comment]
This looks like a bug. It shouldn't be like that. Thanks for reporting.

**Comment by jonathanslenders** [comment]
Should be fixed in: https://github.com/jonathanslenders/python-prompt-toolkit/commit/b57f354933ede8027ec5f1f019f4f9571c7b5514

**Comment by randy3k** [comment]
confirm fixed.
