### ISSUE TITLE
v2.0 does not work on Windows with python 2.7

### ISSUE THREAD

**Issue by randy3k** [jonathanslenders/python-prompt-toolkit#549]
Windows 10
Python 2.7

Code
```python
prompt("> ")
```

here is the error
```python
Traceback (most recent call last):
  File "foo.py", line 3, in <module>
    prompt("> ")
  File "C:\Users\IEUser\Miniconda3\envs\py27\lib\site-packages\prompt_toolkit\shortcuts\prompt.py", line 717, in prompt
    prompt = Prompt()
  File "C:\Users\IEUser\Miniconda3\envs\py27\lib\site-packages\prompt_toolkit\shortcuts\prompt.py", line 256, in __init__
    input = input or get_default_input()
  File "C:\Users\IEUser\Miniconda3\envs\py27\lib\site-packages\prompt_toolkit\input\defaults.py", line 37, in get_default_input
    return create_input()
  File "C:\Users\IEUser\Miniconda3\envs\py27\lib\site-packages\prompt_toolkit\input\defaults.py", line 18, in create_input
    from .win32 import Win32Input
  File "C:\Users\IEUser\Miniconda3\envs\py27\lib\site-packages\prompt_toolkit\input\win32.py", line 227
    yield KeyPress(Keys.BracketedPaste, ''.join(data))
SyntaxError: 'return' with argument inside generator
```

And it is working with python 3.5 on Windows.

**Comment by jonathanslenders** [comment]
Thanks for reporting!

**Comment by jonathanslenders** [comment]
Fixed in: https://github.com/jonathanslenders/python-prompt-toolkit/commit/8679430bb73ea484e7cfa4f02ad287d55ab15511

Can you try again?

**Comment by randy3k** [comment]
It works perfectly, thanks.
