### ISSUE TITLE
Add support for Git shell

### ISSUE THREAD

**Issue by camabeh** [jonathanslenders/python-prompt-toolkit#551]
```python
# prompt_test.py
from prompt_toolkit import prompt

if __name__ == '__main__':
    answer = prompt('Give me some input: ')
    print('You said: %s' % answer)
```

```
$ python prompt_test.py
Traceback (most recent call last):
  File "prompt_test.py", line 4, in <module>
    answer = prompt('Give me some input: ')
  File "Z:\Python3\lib\site-packages\prompt_toolkit\shortcuts.py", line 548, in prompt
    eventloop=eventloop)
  File "Z:\Python3\lib\site-packages\prompt_toolkit\shortcuts.py", line 576, in run_application
    output=create_output(true_color=true_color))
  File "Z:\Python3\lib\site-packages\prompt_toolkit\shortcuts.py", line 118, in create_output
    return Win32Output(stdout)
  File "Z:\Python3\lib\site-packages\prompt_toolkit\terminal\win32_output.py", line 80, in __init__
    info = self.get_win32_screen_buffer_info()
  File "Z:\Python3\lib\site-packages\prompt_toolkit\terminal\win32_output.py", line 172, in get_win32_screen_buffer_info
    raise NoConsoleScreenBufferError
prompt_toolkit.terminal.win32_output.NoConsoleScreenBufferError: Found xterm, while expecting a Windows console. Maybe try to run this program using "winpty" or run it in cmd.exe instead. Or otherwise, in case of Cygwin, use the Python executable that is compiled for Cygwin.
```

Installed python with conda and expected to work with Git shell (bash). Is there any way to run it without replacing python interpreter?

**Comment by jonathanslenders** [comment]
Hi @camabeh, did you try to run it in git-bash using winpty?

**Comment by jonathanslenders** [comment]
Closing this. Feel free to open again if winpty doesn't work.
