### ISSUE TITLE
pt 2.0, Windows: KeyError in wait() callback of Win32AsyncioEventLoop.add_win32_handle()

### ISSUE THREAD

**Issue by jskm** [jonathanslenders/python-prompt-toolkit#564]
While using prompt-toolkit with the asyncio event loop, I keep seeing `ERROR:asyncio:Future exception was never retrieved` caused by a KeyError in [eventloop/asyncio_win32.py#L101](https://github.com/jonathanslenders/python-prompt-toolkit/blob/e4c671e65330b008488a98100368ab24307b47d1/prompt_toolkit/eventloop/asyncio_win32.py#L101)

It happens with the prompts/asyncio-prompt.py example as well. This is an example of the output:
```
(python-prompt-toolkit) PS C:\Code\python-prompt-toolkit\examples\prompts> py .\asyncio-prompt.py
Counter: 0
ERROR:asyncio:Future exception was never retrieved
future: <prompt_toolkit.eventloop.future.Future object at 0x0000000003BBFE48>
Traceback (most recent call last):
  File "C:\Users\jskm\AppData\Local\Programs\Python\Python36\lib\concurrent\futures\thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Code\python-prompt-toolkit\prompt_toolkit\eventloop\asyncio_win32.py", line 101, in wait
    if self._handle_callbacks[handle] != callback:
KeyError: 19
Say something:
You said: ""
Say something:
You said: ""
ERROR:asyncio:Future exception was never retrieved
future: <prompt_toolkit.eventloop.future.Future object at 0x0000000003BDEE80>
Traceback (most recent call last):
  File "C:\Users\jskm\AppData\Local\Programs\Python\Python36\lib\concurrent\futures\thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Code\python-prompt-toolkit\prompt_toolkit\eventloop\asyncio_win32.py", line 101, in wait
    if self._handle_callbacks[handle] != callback:
KeyError: 19
ERROR:asyncio:Future exception was never retrieved
future: <prompt_toolkit.eventloop.future.Future object at 0x0000000003C25EF0>
Traceback (most recent call last):
  File "C:\Users\jskm\AppData\Local\Programs\Python\Python36\lib\concurrent\futures\thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Code\python-prompt-toolkit\prompt_toolkit\eventloop\asyncio_win32.py", line 101, in wait
    if self._handle_callbacks[handle] != callback:
KeyError: 19
Counter: 1
Say something:
You said: ""
Say something:
You said: ""
Say something:
You said: ""
Counter: 2
Say something:
You said: ""
ERROR:asyncio:Future exception was never retrieved
future: <prompt_toolkit.eventloop.future.Future object at 0x0000000003C660F0>
Traceback (most recent call last):
  File "C:\Users\jskm\AppData\Local\Programs\Python\Python36\lib\concurrent\futures\thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Code\python-prompt-toolkit\prompt_toolkit\eventloop\asyncio_win32.py", line 101, in wait
    if self._handle_callbacks[handle] != callback:
KeyError: 19
Say something:
```

**Comment by jonathanslenders** [comment]
Hi @jskm, thanks a lot for reporting this issue. I'll have a look asap. This is clearly a bug.

**Comment by jonathanslenders** [comment]
Hi @jskm: this should be fixed here: https://github.com/jonathanslenders/python-prompt-toolkit/commit/0c0ba71de38fc6222d3e512e6b372d853aee6f6a
Can you try again?

**Comment by jskm** [comment]
Yes, that works.
