### ISSUE TITLE
TypeError: 'unicode' object is not callable in document methods

### ISSUE THREAD

**Issue by rioujin-sou** [jonathanslenders/python-prompt-toolkit#604]
Python 2.7.14
prompt_toolkit 1.0.15

When I try to use the methods **current_line** or **current_line_before_cursor** of the document class to get the text in the current line of the prompt the error TypeError: 'unicode' object is not callable in document methods. However if I use the method **get_word_before_cursor** it works perfectly.

    def get_completions(self, document, complete_event):
        currentCommand = document.current_line()

#> Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/prompt_toolkit/interface.py", line 865, in run
    completions = list(buffer.completer.get_completions(document, complete_event))
  File "/home/rioujin/WindowsShare/Motor/Orchestrator/cliModule_v02.py", line 33, in get_completions
    currentCommand = document.current_line()
TypeError: 'unicode' object is not callable

Thank you for your time.

**Comment by jonathanslenders** [comment]
Hi @rioujin-sou, ``current_line`` is a property, it doesn't need parenthesis to be called.

```python
    currentCommand = document.current_line
```

**Comment by rioujin-sou** [comment]
Thank you very much for your prompt reply. Now it works perfectly.

Regards.

Ivan Reyes
Nokia Packet Core Consultant
