### ISSUE TITLE
error in telnet-chat example : 'CompletionState' object has no attribute 'current_completions'    PYTHON 3.6.3  /  RHEL  

### ISSUE THREAD

**Issue by 0x123451** [jonathanslenders/python-prompt-toolkit#606]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/contrib/telnet/server.py", line 167, in run
    yield From(obj)
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/eventloop/coroutine.py", line 90, in step_next
    new_f = coroutine.throw(exc)
  File "chat-app.py", line 42, in interact
    name = yield From(prompt(message='Type your name: ', async_=True))
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/eventloop/coroutine.py", line 90, in step_next
    new_f = coroutine.throw(exc)
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/shortcuts/prompt.py", line 679, in run_async
    result = yield From(self.app.run_async())
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/eventloop/coroutine.py", line 90, in step_next
    new_f = coroutine.throw(exc)
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/application/application.py", line 617, in _run_async2
    result = yield f
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/eventloop/coroutine.py", line 92, in step_next
    new_f = coroutine.send(f.result())
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/application/application.py", line 583, in _run_async
    self._redraw(render_as_done=True)
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/application/application.py", line 432, in _redraw
    self.renderer.render(self, self.layout, is_done=render_as_done)
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/renderer.py", line 541, in render
    screen.draw_all_floats()
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/layout/screen.py", line 187, in draw_all_floats
    f()
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/layout/containers.py", line 676, in _draw_float
    width = fl.content.preferred_width(write_position.width).preferred
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/layout/containers.py", line 2057, in preferred_width
    if self.filter():
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/filters/base.py", line 131, in __call__
    return all(f() for f in self.filters)
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/filters/base.py", line 131, in <genexpr>
    return all(f() for f in self.filters)
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/filters/base.py", line 214, in __call__
    return self.func()
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/filters/app.py", line 110, in has_completions
    return state is not None and len(state.current_completions) > 0
AttributeError: 'CompletionState' object has no attribute 'current_completions'
'CompletionState' object has no attribute 'current_completions'
INFO:prompt_toolkit.contrib.telnet:Stopping interaction '127.0.0.1' 33632

**Comment by jonathanslenders** [comment]
My mistake, I removed a little too much in a previous commit. Fixed here: https://github.com/jonathanslenders/python-prompt-toolkit/commit/6371de5c6ee5ce60a82a3886dbe334fddccdf970

Thanks for reporting again!

**Comment by 0x123451** [comment]
thanx a lot! only one example from telent not starting hello_wold.py :  
/usr/src/python-prompt-toolkit/examples/telnet# python3.5 hello-world.py 
Traceback (most recent call last):
  File "hello-world.py", line 13, in <module>
    from prompt_toolkit import prompt, clear
ImportError: cannot import name 'clear'
------------------------------------------------------------

**Comment by jonathanslenders** [comment]
And that one is now fixed as well ;) https://github.com/jonathanslenders/python-prompt-toolkit/commit/b895332a3345821dd84d4f8ec84901b25202e856
Thanks!
