### ISSUE TITLE
bug against 1.0

### ISSUE THREAD

**Issue by SolarAquarion** [jonathanslenders/python-prompt-toolkit#633]
vim Exception in thread Thread-38:                              1  12:01 
Traceback (most recent call last):                                            
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner       
    self.run()                                                                
  File "/usr/lib/python3.6/threading.py", line 864, in run                    
    self._target(*self._args, **self._kwargs)                                 
  File "/usr/lib/python3.6/site-packages/prompt_toolkit/interface.py", line 865, in run                                                                       
    completions = list(buffer.completer.get_completions(document, complete_event))                                                                            
  File "/usr/lib/python3.6/site-packages/xonsh/ptk/completer.py", line 82, in get_completions                                                                 
    yield Completion(comp, -l, display=disp)                                  
  File "/usr/lib/python3.6/site-packages/prompt_toolkit/completion.py", line 40, in __init__                                                                  
    assert self.start_position <= 0                               
AssertionError

**Comment by jonathanslenders** [comment]
Hi @SolarAquarion,
This looks like a bug in Xonsh. Could you report it in their repository?
Thanks!

**Comment by lwm** [comment]
Agreed, looks to be an upstream bug. Should be closed here.
