### ISSUE TITLE
v2.0.2 fails at python 2 on windows 

### ISSUE THREAD

**Issue by randy3k** [jonathanslenders/python-prompt-toolkit#634]
Just
```
from prompt_toolkit import prompt
prompt("> ")
```

Error
```
Traceback (most recent call last):
  File "foo.py", line 3, in <module>
    prompt("> ")
  File "C:\Users\IEUser\Miniconda2\lib\site-packages\prompt_toolkit\shortcuts\prompt.py", line 792, in prompt
    session = PromptSession(input=input, output=output)
  File "C:\Users\IEUser\Miniconda2\lib\site-packages\prompt_toolkit\shortcuts\prompt.py", line 305, in __init__
    self.layout = self._create_layout()
  File "C:\Users\IEUser\Miniconda2\lib\site-packages\prompt_toolkit\shortcuts\prompt.py", line 485, in _create_layout
    ~multi_column_complete_style)),
  File "C:\Users\IEUser\Miniconda2\lib\site-packages\prompt_toolkit\layout\menus.py", line 196, in __init__
    z_index=z_index,
  File "C:\Users\IEUser\Miniconda2\lib\site-packages\prompt_toolkit\layout\containers.py", line 1200, in __init__
    assert z_index is None or isinstance(z_index, int)
AssertionError
```

It works on python 3 on windows or python 2 on macOS though.

**Comment by randy3k** [comment]
It is because [10**10](https://github.com/randy3k/lineedit/blob/c11073fcd553228f4e80252f9030d2fa3277d008/lineedit/deps/prompt_toolkit/layout/menus.py#L183-L183) is long at python 2 on windows.

**Comment by randy3k** [comment]
It seems there are more bugs. I still get this after fixing the `long` bug.

```
λ python foo.py
Traceback (most recent call last):
  File "foo.py", line 5, in <module>
    prompt(u"> ")
  File "d:\lineedit\lineedit\deps\prompt_toolkit\shortcuts\prompt.py", line 793, in prompt
    return session.prompt(*a, **kw)
  File "d:\lineedit\lineedit\deps\prompt_toolkit\shortcuts\prompt.py", line 722, in prompt
    return run_sync()
  File "d:\lineedit\lineedit\deps\prompt_toolkit\shortcuts\prompt.py", line 706, in run_sync
    return self.app.run(inputhook=self.inputhook)
  File "d:\lineedit\lineedit\deps\prompt_toolkit\application\application.py", line 682, in run
    return run()
  File "d:\lineedit\lineedit\deps\prompt_toolkit\application\application.py", line 656, in run
    return f.result()
  File "d:\lineedit\lineedit\deps\prompt_toolkit\eventloop\future.py", line 149, in result
    raise self._exception
AssertionError
```
