### ISSUE TITLE
Debugging under Vim

### ISSUE THREAD

**Issue by techtonik** [jonathanslenders/python-prompt-toolkit#648]
`prompt_toolkit` fails if run under `vim`. Example:
```
#!/usr/bin/env python3

import os

from prompt_toolkit import prompt

import sys

print(sys.stdin.isatty())
print(sys.stdout.isatty())

text = prompt(os.getcwd())
print("[debug] " + text)
```
Output:
```
:!./notfar.py

False
False
Traceback (most recent call last):
  File "./notfar.py", line 12, in <module>
    text = prompt(os.getcwd())
  File "/usr/lib/python3.6/site-packages/prompt_toolkit/shortcuts.py", line 548, in
    eventloop=eventloop)
  File "/usr/lib/python3.6/site-packages/prompt_toolkit/shortcuts.py", line 576, in
    output=create_output(true_color=true_color))
  File "/usr/lib/python3.6/site-packages/prompt_toolkit/shortcuts.py", line 126, in
    ansi_colors_only=ansi_colors_only, term=term)
  File "/usr/lib/python3.6/site-packages/prompt_toolkit/terminal/vt100_output.py", l
    assert stdout.isatty()
AssertionError
shell returned 1
```

**Comment by jonathanslenders** [comment]
Hi @techtonik,

What operating system or Linux distribution and which Vim version do you have?

When I try this, it works fine. In any case, this is not an issue with prompt_toolkit.
Vim is responsible for running that subprocess in a pty, or maybe Vim itself didn't run in a pty to begin with.

Jonathan

**Comment by techtonik** [comment]
Fedora 28. Tilix terminal.
```
✗ vim --version
NVIM v0.2.2
Build type: RelWithDebInfo
Lua 5.3
Compilation: /usr/bin/cc -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -Wconversion -Wp,-U_FORTIFY_SOURCE -Wp,-D_FORTIFY_SOURCE=1 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/builddir/build/BUILD/neovim-0.2.2/build/config -I/builddir/build/BUILD/neovim-0.2.2/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/builddir/build/BUILD/neovim-0.2.2/build/src/nvim/auto -I/builddir/build/BUILD/neovim-0.2.2/build/include
Compiled by mockbuild

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
✗ echo $TERM
xterm-256color
```

**Comment by techtonik** [comment]
It looks that I've got `neovim` instead of `vim`, and it was not installed via standard package.
```
✗ rpm -qf `which vim`
file /usr/bin/vim is not owned by any package
```
Let me reinstall it and try again.

**Comment by techtonik** [comment]
Everything is okay with plain Vim 8.1.055.

**Comment by techtonik** [comment]
Looks like it is a [https://github.com/neovim/neovim/issues/1496#issuecomment-63691483](design decision) in hope for a better terminal-user interface/experience. A pity that it took so much time.
