### ISSUE TITLE
AttributeError: 'TextArea' object has no attribute 'get_children'

### ISSUE THREAD

**Issue by lwm** [jonathanslenders/python-prompt-toolkit#668]
I'm running the latest HEAD of python-prompt-toolkit.

The stack trace is:

```
Traceback (most recent call last):
  File "xpub_lib_termz.py", line 126, in <module>
    run()
  File "xpub_lib_termz.py", line 112, in run
    focused_element=command_prompt
  File "/home/decentral1se/.local/share/virtualenvs/xpub-lib-termz-Dd1FRwsF/lib/python3.6/site-packages/prompt_toolkit/layout/layout.py", line 49, in __init__
    self.focus(focused_element)
  File "/home/decentral1se/.local/share/virtualenvs/xpub-lib-termz-Dd1FRwsF/lib/python3.6/site-packages/prompt_toolkit/layout/layout.py", line 126, in focus
    for c in walk(value, skip_hidden=True):
  File "/home/decentral1se/.local/share/virtualenvs/xpub-lib-termz-Dd1FRwsF/lib/python3.6/site-packages/prompt_toolkit/layout/layout.py", line 380, in walk
    for i in walk(c, skip_hidden=skip_hidden):
  File "/home/decentral1se/.local/share/virtualenvs/xpub-lib-termz-Dd1FRwsF/lib/python3.6/site-packages/prompt_toolkit/layout/layout.py", line 380, in walk
    for i in walk(c, skip_hidden=skip_hidden):
  File "/home/decentral1se/.local/share/virtualenvs/xpub-lib-termz-Dd1FRwsF/lib/python3.6/site-packages/prompt_toolkit/layout/layout.py", line 378, in walk
    for c in container.get_children():
  File "/home/decentral1se/.local/share/virtualenvs/xpub-lib-termz-Dd1FRwsF/lib/python3.6/site-packages/prompt_toolkit/layout/containers.py", line 2110, in get_children
    return self.get_container().get_children()
AttributeError: 'TextArea' object has no attribute 'get_children'
```

Looks like this is the culprit:

https://github.com/jonathanslenders/python-prompt-toolkit/blob/c37cc6e805ff3df9ea79ae0b1bbc95995ba0e5b8/prompt_toolkit/layout/containers.py#L2110

**Comment by lwm** [comment]
Removing the `focused_element=command_prompt`, I then see:

```
Traceback (most recent call last):
  File "xpub_lib_termz.py", line 126, in <module>
    run()
  File "xpub_lib_termz.py", line 115, in run
    full_screen=True
  File "/home/decentral1se/.local/share/virtualenvs/xpub-lib-termz-Dd1FRwsF/lib/python3.6/site-packages/prompt_toolkit/application/application.py", line 260, in __init__
    self.reset()
  File "/home/decentral1se/.local/share/virtualenvs/xpub-lib-termz-Dd1FRwsF/lib/python3.6/site-packages/prompt_toolkit/application/application.py", line 334, in reset
    self.layout.reset()
  File "/home/decentral1se/.local/share/virtualenvs/xpub-lib-termz-Dd1FRwsF/lib/python3.6/site-packages/prompt_toolkit/layout/layout.py", line 349, in reset
    return self.container.reset()
  File "/home/decentral1se/.local/share/virtualenvs/xpub-lib-termz-Dd1FRwsF/lib/python3.6/site-packages/prompt_toolkit/layout/containers.py", line 430, in reset
    c.reset()
  File "/home/decentral1se/.local/share/virtualenvs/xpub-lib-termz-Dd1FRwsF/lib/python3.6/site-packages/prompt_toolkit/layout/containers.py", line 233, in reset
    c.reset()
  File "/home/decentral1se/.local/share/virtualenvs/xpub-lib-termz-Dd1FRwsF/lib/python3.6/site-packages/prompt_toolkit/layout/containers.py", line 233, in reset
    c.reset()
  File "/home/decentral1se/.local/share/virtualenvs/xpub-lib-termz-Dd1FRwsF/lib/python3.6/site-packages/prompt_toolkit/layout/containers.py", line 430, in reset
    c.reset()
  File "/home/decentral1se/.local/share/virtualenvs/xpub-lib-termz-Dd1FRwsF/lib/python3.6/site-packages/prompt_toolkit/layout/containers.py", line 2092, in reset
    self.get_container().reset()
AttributeError: 'TextArea' object has no attribute 'reset'
```

There seems to be a missing API for the `DynamicContainer` and `TextArea`?

**Comment by jonathanslenders** [comment]
Hi @lwm,
What is the parent control of this TextArea?
I think the problem is that a ``TextArea`` is not a real container object itself. (It doesn't implement the ``Container`` ABC). But it has a ``__pt_container__`` method that should return the actual container. The ``to_container`` helper is supposed to do that, and I think this is missing from the parent control.

**Comment by lwm** [comment]
Aha, I see. Is this another instance of https://github.com/jonathanslenders/python-prompt-toolkit/issues/667?

```
    command_prompt = Frame(
        title='COMMAND SHELL',
        body=FloatContainer(
            content=prompt_buffer,
            floats=[
                Float(
                    xcursor=True,
                    ycursor=True,
                    content=CompletionsMenu(max_height=5, scroll_offset=1)
                )
            ]
        ),
    )
```

Which is then passed to the application where it blows up on `run()`:

```
    application = Application(
        layout=Layout(
            container,
            focused_element=command_prompt
        ),
        key_bindings=bindings,
        full_screen=True
    )
```

**Comment by jonathanslenders** [comment]
Hi @lwm,
I just pushed this commit: https://github.com/jonathanslenders/python-prompt-toolkit/commit/1d6c25655fbf107a00cf64adf5624050cf8c5f30
Can you try again?

**Comment by lwm** [comment]
Oh yes, thank you very much, that works perfectly!

**Comment by jonathanslenders** [comment]
Well, thank you for reporting the bug!
