### ISSUE TITLE
AssertionError hiding my mistake

### ISSUE THREAD

**Issue by boxed** [jonathanslenders/python-prompt-toolkit#727]
I accidentally returned an internal type instead of a str from my custom completer and got this exception:

```
Traceback (most recent call last):
  File "doc_prompt_toolkit.py", line 25, in <module>
    text = prompt('Column', completer=completer, bottom_toolbar='. to see shortcuts, ( to see constructor arguments')
  File "/Users/andersh/Projects/tri.table/venv/lib/python2.7/site-packages/prompt_toolkit/shortcuts/prompt.py", line 803, in prompt
    return session.prompt(*a, **kw)
  File "/Users/andersh/Projects/tri.table/venv/lib/python2.7/site-packages/prompt_toolkit/shortcuts/prompt.py", line 731, in prompt
    return run_sync()
  File "/Users/andersh/Projects/tri.table/venv/lib/python2.7/site-packages/prompt_toolkit/shortcuts/prompt.py", line 715, in run_sync
    return self.app.run(inputhook=self.inputhook, pre_run=pre_run)
  File "/Users/andersh/Projects/tri.table/venv/lib/python2.7/site-packages/prompt_toolkit/application/application.py", line 682, in run
    return run()
  File "/Users/andersh/Projects/tri.table/venv/lib/python2.7/site-packages/prompt_toolkit/application/application.py", line 656, in run
    return f.result()
  File "/Users/andersh/Projects/tri.table/venv/lib/python2.7/site-packages/prompt_toolkit/eventloop/future.py", line 149, in result
    raise self._exception
AssertionError
```

The original assertion error stack trace is lost. So I fiddled with the code and made it not catch this exception and store it and then I got:

```
Traceback (most recent call last):
  File "doc_prompt_toolkit.py", line 27, in <module>
    text = prompt('Column', completer=completer, bottom_toolbar='. to see shortcuts, ( to see constructor arguments')
  File "/Users/andersh/Projects/tri.table/venv/lib/python2.7/site-packages/prompt_toolkit/shortcuts/prompt.py", line 803, in prompt
    return session.prompt(*a, **kw)
  File "/Users/andersh/Projects/tri.table/venv/lib/python2.7/site-packages/prompt_toolkit/shortcuts/prompt.py", line 731, in prompt
    return run_sync()
  File "/Users/andersh/Projects/tri.table/venv/lib/python2.7/site-packages/prompt_toolkit/shortcuts/prompt.py", line 715, in run_sync
    return self.app.run(inputhook=self.inputhook, pre_run=pre_run)
  File "/Users/andersh/Projects/tri.table/venv/lib/python2.7/site-packages/prompt_toolkit/application/application.py", line 682, in run
    return run()
  File "/Users/andersh/Projects/tri.table/venv/lib/python2.7/site-packages/prompt_toolkit/application/application.py", line 654, in run
    f = self.run_async(pre_run=pre_run)
  File "/Users/andersh/Projects/tri.table/venv/lib/python2.7/site-packages/prompt_toolkit/application/application.py", line 640, in run_async
    return ensure_future(_run_async2())
  File "/Users/andersh/Projects/tri.table/venv/lib/python2.7/site-packages/prompt_toolkit/eventloop/coroutine.py", line 21, in ensure_future
    return _run_coroutine(future_or_coroutine)
  File "/Users/andersh/Projects/tri.table/venv/lib/python2.7/site-packages/prompt_toolkit/eventloop/coroutine.py", line 115, in _run_coroutine
    step_next()
  File "/Users/andersh/Projects/tri.table/venv/lib/python2.7/site-packages/prompt_toolkit/eventloop/coroutine.py", line 104, in step_next
    ref.future.set_exception(e)
  File "/Users/andersh/Projects/tri.table/venv/lib/python2.7/site-packages/prompt_toolkit/eventloop/coroutine.py", line 86, in step_next
    new_f = coroutine.send(None)
  File "/Users/andersh/Projects/tri.table/venv/lib/python2.7/site-packages/prompt_toolkit/application/application.py", line 637, in _run_async2
    assert not self._is_running
AssertionError
```

This isn't very helpful either, the original exception is still gone! So I commented out this assertion and then I got the real error:

```
  File "/Users/andersh/Projects/tri.table/venv/lib/python2.7/site-packages/prompt_toolkit/formatted_text/base.py", line 50, in to_formatted_text
    'HTML, ANSI or a FormattedText instance. Got %r' % value)
ValueError: No formatted text. Expecting a unicode object, HTML, ANSI or a FormattedText instance. Got 'Column'
```

That error message is very helpful but it was very hard to get to it. It would have been better to print that exception and stack trace and directly doing exit(1) for example.

**Comment by boxed** [comment]
Actually, something seems to be wrong with that exception too, because if I return a str object in Python3 I still get that error. This seems wrong. Example code:

```
class TriCompleter(Completer):
    def get_completions(self, document, complete_event):

        yield Completion('asd', 0, display='foo')


completer = TriCompleter()

text = prompt('Column', completer=completer, bottom_toolbar='. to see shortcuts, ( to see constructor arguments')

print('You said: %s' % text)
```

**Comment by boxed** [comment]
> In Python 3, all the exceptions are chained and will be printed.


Ah. Cool. I was using Python 2 accidentally the whole time actually. 
> For Python 2, you can disable the assertions by passing the -O option to the Python interpreter.
> 
Hmmm... that’s an interesting solution. It seems wrong to me to use the optimize flag to make the code more debuggable though :P

> I think that the object that you have there is a str in Python 2 instead of a unicode object. Maybe try to use either from __future__ import unicode_literals, or prefix 'Column' with a u : u'Column'
> 

Yep, that was it. In Python 3 things are more sane. I just worry that to make this thing work in Python 2 I’m going to have a hard time. 

What is the reason str isn’t an allowed output string type in Python 2? Seems very strange.

**Comment by jonathanslenders** [comment]
>> Hmmm... that’s an interesting solution. It seems wrong to me to use the optimize flag to make the code more debuggable though :P

Yes, true, I agree it's weird. It is because of the execution order and Python2's lack of chaining the exceptions. In a future release we will drop Python 2 support and turn this into type annotations.

>>  What is the reason str isn’t an allowed output string type in Python 2? Seems very strange.

Str isn't allowed, because this can result in many subtle bugs. For instance, cursor movements can't be calculated correctly, because we don't know which bytes belong together in multi byte characters. Or many run-time bugs because of implicit decoding when concatenating against unicode characters. Much easier to say is that you have to pass a decoded string. If your application uses str everywhere, then call str.decode before passing it to prompt_toolkit.

**Comment by boxed** [comment]
Decoding str on the way in would make this nicer I think. In any case, if the idea is to drop py2 soon anyway this is all pretty irrelevant.

**Comment by jonathanslenders** [comment]
Closing this. Feel free to open again if needed.
