### ISSUE TITLE
Cannot open ptpython after installation.

### ISSUE THREAD

**Issue by c02y** [jonathanslenders/python-prompt-toolkit#73]
I use the

    sudo pip install ptpyton

suggested in your [README.rst](https://github.com/jonathanslenders/python-prompt-toolkit#installation). But after execute in terminal, the output is this:

    Traceback (most recent call last):
      File "/usr/bin/ptpython", line 9, in <module>
        load_entry_point('prompt-toolkit==0.25', 'console_scripts', 'ptpython')()
      File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 348, in load_entry_point
        return get_distribution(dist).load_entry_point(group, name)
      File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2311, in load_entry_point
        return ep.load()
      File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2025, in load
        entry = __import__(self.module_name, globals(),globals(), ['__name__'])
      File "/usr/lib/python2.7/site-packages/prompt_toolkit/contrib/entry_points/ptpython.py", line 26, in <module>
        from prompt_toolkit.contrib.repl import embed
      File "/usr/lib/python2.7/site-packages/prompt_toolkit/contrib/repl.py", line 20, in <module>
        from prompt_toolkit.contrib.python_input import PythonCommandLineInterface, PythonStyle, AutoCompletionStyle
      File "/usr/lib/python2.7/site-packages/prompt_toolkit/contrib/python_input.py", line 37, in <module>
        import jedi
      File "/usr/lib/python2.7/site-packages/jedi/__init__.py", line 45, in <module>
        from .api import Script, Interpreter, NotFoundError, set_debug_function
      File "/usr/lib/python2.7/site-packages/jedi/api/__init__.py", line 18, in <module>
        from jedi.parser import Parser
      File "/usr/lib/python2.7/site-packages/jedi/parser/__init__.py", line 23, in <module>
        from jedi.parser import representation as pr
      File "/usr/lib/python2.7/site-packages/jedi/parser/representation.py", line 41, in <module>
        from jedi._compatibility import (next, Python3Method, encoding, unicode,
    ImportError: cannot import name is_py3

FYI: 

It works fine when I'm using Fedora 20, but now it outputs errors like above after upgrading to Fedora 21. I've tried to uninstall it, but it doesn't work.

**Comment by jonathanslenders** [comment]
Glad you figured this out!
And thanks for telling me what you did!
